// AUTO-GENERATED by scripts/generate-maps.ts — do not edit by hand.
// Regenerate with: pnpm --filter @lor/shared generate-maps
import type { GameMap } from './types';

export const SMALL_MAP: GameMap = {
  "id": "small",
  "name": "Small Realm",
  "width": 1200,
  "height": 900,
  "counties": [
    {
      "id": "northumberland",
      "name": "Northumberland",
      "polygon": [
        {
          "x": 559,
          "y": 277
        },
        {
          "x": 504,
          "y": 161
        },
        {
          "x": 557,
          "y": 87
        },
        {
          "x": 674,
          "y": 83
        },
        {
          "x": 744,
          "y": 172
        },
        {
          "x": 745,
          "y": 212
        }
      ],
      "centroid": {
        "x": 621,
        "y": 172
      },
      "neighbors": [
        "cumberland",
        "yorkshire"
      ]
    },
    {
      "id": "cumberland",
      "name": "Cumberland",
      "polygon": [
        {
          "x": 550,
          "y": 304
        },
        {
          "x": 343,
          "y": 334
        },
        {
          "x": 336,
          "y": 323
        },
        {
          "x": 343,
          "y": 221
        },
        {
          "x": 441,
          "y": 149
        },
        {
          "x": 504,
          "y": 161
        },
        {
          "x": 559,
          "y": 277
        }
      ],
      "centroid": {
        "x": 442,
        "y": 248
      },
      "neighbors": [
        "northumberland",
        "yorkshire",
        "lancashire"
      ]
    },
    {
      "id": "yorkshire",
      "name": "Yorkshire",
      "polygon": [
        {
          "x": 550,
          "y": 304
        },
        {
          "x": 559,
          "y": 277
        },
        {
          "x": 745,
          "y": 212
        },
        {
          "x": 779,
          "y": 248
        },
        {
          "x": 719,
          "y": 458
        },
        {
          "x": 575,
          "y": 398
        }
      ],
      "centroid": {
        "x": 668,
        "y": 329
      },
      "neighbors": [
        "northumberland",
        "cumberland",
        "lancashire",
        "lincolnshire",
        "warwickshire"
      ]
    },
    {
      "id": "lancashire",
      "name": "Lancashire",
      "polygon": [
        {
          "x": 483,
          "y": 503
        },
        {
          "x": 333,
          "y": 516
        },
        {
          "x": 343,
          "y": 334
        },
        {
          "x": 550,
          "y": 304
        },
        {
          "x": 575,
          "y": 398
        }
      ],
      "centroid": {
        "x": 445,
        "y": 408
      },
      "neighbors": [
        "cumberland",
        "yorkshire",
        "warwickshire",
        "gloucestershire"
      ]
    },
    {
      "id": "lincolnshire",
      "name": "Lincolnshire",
      "polygon": [
        {
          "x": 719,
          "y": 458
        },
        {
          "x": 779,
          "y": 248
        },
        {
          "x": 861,
          "y": 266
        },
        {
          "x": 935,
          "y": 354
        },
        {
          "x": 831,
          "y": 490
        },
        {
          "x": 745,
          "y": 497
        }
      ],
      "centroid": {
        "x": 818,
        "y": 377
      },
      "neighbors": [
        "yorkshire",
        "norfolk",
        "warwickshire",
        "essex"
      ]
    },
    {
      "id": "norfolk",
      "name": "Norfolk",
      "polygon": [
        {
          "x": 831,
          "y": 490
        },
        {
          "x": 935,
          "y": 354
        },
        {
          "x": 956,
          "y": 356
        },
        {
          "x": 1035,
          "y": 438
        },
        {
          "x": 1009,
          "y": 558
        },
        {
          "x": 959,
          "y": 590
        }
      ],
      "centroid": {
        "x": 945,
        "y": 473
      },
      "neighbors": [
        "lincolnshire",
        "essex"
      ]
    },
    {
      "id": "warwickshire",
      "name": "Warwickshire",
      "polygon": [
        {
          "x": 483,
          "y": 503
        },
        {
          "x": 575,
          "y": 398
        },
        {
          "x": 719,
          "y": 458
        },
        {
          "x": 745,
          "y": 497
        },
        {
          "x": 658,
          "y": 730
        }
      ],
      "centroid": {
        "x": 623,
        "y": 539
      },
      "neighbors": [
        "yorkshire",
        "lancashire",
        "lincolnshire",
        "gloucestershire",
        "essex"
      ]
    },
    {
      "id": "gloucestershire",
      "name": "Gloucestershire",
      "polygon": [
        {
          "x": 483,
          "y": 503
        },
        {
          "x": 658,
          "y": 730
        },
        {
          "x": 658,
          "y": 732
        },
        {
          "x": 616,
          "y": 770
        },
        {
          "x": 573,
          "y": 788
        },
        {
          "x": 278,
          "y": 583
        },
        {
          "x": 284,
          "y": 565
        },
        {
          "x": 333,
          "y": 516
        }
      ],
      "centroid": {
        "x": 474,
        "y": 631
      },
      "neighbors": [
        "lancashire",
        "warwickshire",
        "essex",
        "devon"
      ]
    },
    {
      "id": "essex",
      "name": "Essex",
      "polygon": [
        {
          "x": 658,
          "y": 730
        },
        {
          "x": 745,
          "y": 497
        },
        {
          "x": 831,
          "y": 490
        },
        {
          "x": 959,
          "y": 590
        },
        {
          "x": 950,
          "y": 640
        },
        {
          "x": 667,
          "y": 734
        },
        {
          "x": 658,
          "y": 732
        }
      ],
      "centroid": {
        "x": 805,
        "y": 607
      },
      "neighbors": [
        "lincolnshire",
        "norfolk",
        "warwickshire",
        "gloucestershire",
        "kent"
      ]
    },
    {
      "id": "kent",
      "name": "Kent",
      "polygon": [
        {
          "x": 667,
          "y": 734
        },
        {
          "x": 950,
          "y": 640
        },
        {
          "x": 978,
          "y": 702
        },
        {
          "x": 926,
          "y": 810
        },
        {
          "x": 810,
          "y": 825
        }
      ],
      "centroid": {
        "x": 849,
        "y": 739
      },
      "neighbors": [
        "essex"
      ]
    },
    {
      "id": "devon",
      "name": "Devon",
      "polygon": [
        {
          "x": 278,
          "y": 583
        },
        {
          "x": 573,
          "y": 788
        },
        {
          "x": 476,
          "y": 886
        },
        {
          "x": 404,
          "y": 900
        },
        {
          "x": 383,
          "y": 900
        },
        {
          "x": 227,
          "y": 646
        },
        {
          "x": 228,
          "y": 640
        }
      ],
      "centroid": {
        "x": 390,
        "y": 754
      },
      "neighbors": [
        "gloucestershire",
        "cornwall"
      ]
    },
    {
      "id": "cornwall",
      "name": "Cornwall",
      "polygon": [
        {
          "x": 227,
          "y": 646
        },
        {
          "x": 383,
          "y": 900
        },
        {
          "x": 189,
          "y": 900
        },
        {
          "x": 146,
          "y": 762
        }
      ],
      "centroid": {
        "x": 247,
        "y": 804
      },
      "neighbors": [
        "devon"
      ]
    }
  ]
};

export const REALM_MAP: GameMap = {
  "id": "realm",
  "name": "Realm of England",
  "width": 1600,
  "height": 1000,
  "counties": [
    {
      "id": "northumberland",
      "name": "Northumberland",
      "polygon": [
        {
          "x": 746,
          "y": 232
        },
        {
          "x": 710,
          "y": 104
        },
        {
          "x": 712,
          "y": 101
        },
        {
          "x": 829,
          "y": 54
        },
        {
          "x": 930,
          "y": 108
        },
        {
          "x": 961,
          "y": 178
        }
      ],
      "centroid": {
        "x": 826,
        "y": 143
      },
      "neighbors": [
        "cumberland",
        "durham"
      ]
    },
    {
      "id": "cumberland",
      "name": "Cumberland",
      "polygon": [
        {
          "x": 735,
          "y": 264
        },
        {
          "x": 528,
          "y": 291
        },
        {
          "x": 522,
          "y": 218
        },
        {
          "x": 583,
          "y": 123
        },
        {
          "x": 710,
          "y": 104
        },
        {
          "x": 746,
          "y": 232
        }
      ],
      "centroid": {
        "x": 635,
        "y": 203
      },
      "neighbors": [
        "northumberland",
        "durham",
        "lancashire"
      ]
    },
    {
      "id": "durham",
      "name": "Durham",
      "polygon": [
        {
          "x": 772,
          "y": 349
        },
        {
          "x": 735,
          "y": 264
        },
        {
          "x": 746,
          "y": 232
        },
        {
          "x": 961,
          "y": 178
        },
        {
          "x": 982,
          "y": 197
        },
        {
          "x": 997,
          "y": 237
        },
        {
          "x": 817,
          "y": 357
        }
      ],
      "centroid": {
        "x": 857,
        "y": 262
      },
      "neighbors": [
        "northumberland",
        "cumberland",
        "yorkshire",
        "lancashire",
        "derbyshire"
      ]
    },
    {
      "id": "yorkshire",
      "name": "Yorkshire",
      "polygon": [
        {
          "x": 878,
          "y": 418
        },
        {
          "x": 817,
          "y": 357
        },
        {
          "x": 997,
          "y": 237
        },
        {
          "x": 1033,
          "y": 276
        },
        {
          "x": 996,
          "y": 373
        }
      ],
      "centroid": {
        "x": 936,
        "y": 334
      },
      "neighbors": [
        "durham",
        "derbyshire",
        "nottinghamshire",
        "lincolnshire"
      ]
    },
    {
      "id": "lancashire",
      "name": "Lancashire",
      "polygon": [
        {
          "x": 730,
          "y": 416
        },
        {
          "x": 513,
          "y": 373
        },
        {
          "x": 512,
          "y": 322
        },
        {
          "x": 528,
          "y": 291
        },
        {
          "x": 735,
          "y": 264
        },
        {
          "x": 772,
          "y": 349
        }
      ],
      "centroid": {
        "x": 647,
        "y": 338
      },
      "neighbors": [
        "cumberland",
        "durham",
        "cheshire",
        "derbyshire"
      ]
    },
    {
      "id": "cheshire",
      "name": "Cheshire",
      "polygon": [
        {
          "x": 730,
          "y": 445
        },
        {
          "x": 679,
          "y": 521
        },
        {
          "x": 490,
          "y": 437
        },
        {
          "x": 513,
          "y": 373
        },
        {
          "x": 730,
          "y": 416
        }
      ],
      "centroid": {
        "x": 616,
        "y": 440
      },
      "neighbors": [
        "lancashire",
        "derbyshire",
        "shropshire",
        "staffordshire"
      ]
    },
    {
      "id": "derbyshire",
      "name": "Derbyshire",
      "polygon": [
        {
          "x": 836,
          "y": 524
        },
        {
          "x": 730,
          "y": 445
        },
        {
          "x": 730,
          "y": 416
        },
        {
          "x": 772,
          "y": 349
        },
        {
          "x": 817,
          "y": 357
        },
        {
          "x": 878,
          "y": 418
        },
        {
          "x": 883,
          "y": 477
        }
      ],
      "centroid": {
        "x": 809,
        "y": 433
      },
      "neighbors": [
        "durham",
        "yorkshire",
        "lancashire",
        "cheshire",
        "nottinghamshire",
        "staffordshire",
        "leicestershire"
      ]
    },
    {
      "id": "nottinghamshire",
      "name": "Nottinghamshire",
      "polygon": [
        {
          "x": 1018,
          "y": 518
        },
        {
          "x": 883,
          "y": 477
        },
        {
          "x": 878,
          "y": 418
        },
        {
          "x": 996,
          "y": 373
        },
        {
          "x": 1019,
          "y": 518
        }
      ],
      "centroid": {
        "x": 953,
        "y": 447
      },
      "neighbors": [
        "yorkshire",
        "derbyshire",
        "lincolnshire",
        "leicestershire",
        "cambridgeshire"
      ]
    },
    {
      "id": "lincolnshire",
      "name": "Lincolnshire",
      "polygon": [
        {
          "x": 996,
          "y": 373
        },
        {
          "x": 1033,
          "y": 276
        },
        {
          "x": 1071,
          "y": 285
        },
        {
          "x": 1189,
          "y": 388
        },
        {
          "x": 1192,
          "y": 397
        },
        {
          "x": 1109,
          "y": 513
        },
        {
          "x": 1019,
          "y": 518
        }
      ],
      "centroid": {
        "x": 1079,
        "y": 404
      },
      "neighbors": [
        "yorkshire",
        "nottinghamshire",
        "norfolk",
        "cambridgeshire"
      ]
    },
    {
      "id": "shropshire",
      "name": "Shropshire",
      "polygon": [
        {
          "x": 684,
          "y": 605
        },
        {
          "x": 677,
          "y": 623
        },
        {
          "x": 665,
          "y": 624
        },
        {
          "x": 420,
          "y": 526
        },
        {
          "x": 490,
          "y": 437
        },
        {
          "x": 679,
          "y": 521
        }
      ],
      "centroid": {
        "x": 565,
        "y": 530
      },
      "neighbors": [
        "cheshire",
        "staffordshire",
        "herefordshire",
        "warwickshire",
        "gloucestershire"
      ]
    },
    {
      "id": "staffordshire",
      "name": "Staffordshire",
      "polygon": [
        {
          "x": 834,
          "y": 555
        },
        {
          "x": 684,
          "y": 605
        },
        {
          "x": 679,
          "y": 521
        },
        {
          "x": 730,
          "y": 445
        },
        {
          "x": 836,
          "y": 524
        }
      ],
      "centroid": {
        "x": 747,
        "y": 530
      },
      "neighbors": [
        "cheshire",
        "derbyshire",
        "shropshire",
        "leicestershire",
        "warwickshire"
      ]
    },
    {
      "id": "leicestershire",
      "name": "Leicestershire",
      "polygon": [
        {
          "x": 834,
          "y": 555
        },
        {
          "x": 836,
          "y": 524
        },
        {
          "x": 883,
          "y": 477
        },
        {
          "x": 1018,
          "y": 518
        },
        {
          "x": 1005,
          "y": 550
        },
        {
          "x": 865,
          "y": 603
        }
      ],
      "centroid": {
        "x": 914,
        "y": 537
      },
      "neighbors": [
        "derbyshire",
        "nottinghamshire",
        "staffordshire",
        "warwickshire",
        "northamptonshire",
        "cambridgeshire"
      ]
    },
    {
      "id": "norfolk",
      "name": "Norfolk",
      "polygon": [
        {
          "x": 1109,
          "y": 513
        },
        {
          "x": 1192,
          "y": 397
        },
        {
          "x": 1270,
          "y": 440
        },
        {
          "x": 1303,
          "y": 536
        },
        {
          "x": 1280,
          "y": 586
        },
        {
          "x": 1152,
          "y": 576
        }
      ],
      "centroid": {
        "x": 1211,
        "y": 504
      },
      "neighbors": [
        "lincolnshire",
        "cambridgeshire",
        "suffolk"
      ]
    },
    {
      "id": "herefordshire",
      "name": "Herefordshire",
      "polygon": [
        {
          "x": 665,
          "y": 624
        },
        {
          "x": 538,
          "y": 719
        },
        {
          "x": 387,
          "y": 690
        },
        {
          "x": 325,
          "y": 647
        },
        {
          "x": 325,
          "y": 645
        },
        {
          "x": 374,
          "y": 557
        },
        {
          "x": 420,
          "y": 526
        }
      ],
      "centroid": {
        "x": 478,
        "y": 629
      },
      "neighbors": [
        "shropshire",
        "gloucestershire",
        "somerset",
        "devon"
      ]
    },
    {
      "id": "warwickshire",
      "name": "Warwickshire",
      "polygon": [
        {
          "x": 834,
          "y": 555
        },
        {
          "x": 865,
          "y": 603
        },
        {
          "x": 865,
          "y": 641
        },
        {
          "x": 737,
          "y": 698
        },
        {
          "x": 716,
          "y": 689
        },
        {
          "x": 677,
          "y": 623
        },
        {
          "x": 684,
          "y": 605
        }
      ],
      "centroid": {
        "x": 775,
        "y": 626
      },
      "neighbors": [
        "shropshire",
        "staffordshire",
        "leicestershire",
        "northamptonshire",
        "gloucestershire",
        "oxfordshire",
        "wiltshire"
      ]
    },
    {
      "id": "northamptonshire",
      "name": "Northamptonshire",
      "polygon": [
        {
          "x": 865,
          "y": 603
        },
        {
          "x": 1005,
          "y": 550
        },
        {
          "x": 1012,
          "y": 637
        },
        {
          "x": 915,
          "y": 702
        },
        {
          "x": 865,
          "y": 641
        }
      ],
      "centroid": {
        "x": 941,
        "y": 624
      },
      "neighbors": [
        "leicestershire",
        "warwickshire",
        "cambridgeshire",
        "oxfordshire",
        "hertfordshire"
      ]
    },
    {
      "id": "cambridgeshire",
      "name": "Cambridgeshire",
      "polygon": [
        {
          "x": 1018,
          "y": 518
        },
        {
          "x": 1019,
          "y": 518
        },
        {
          "x": 1109,
          "y": 513
        },
        {
          "x": 1152,
          "y": 576
        },
        {
          "x": 1133,
          "y": 652
        },
        {
          "x": 1072,
          "y": 686
        },
        {
          "x": 1012,
          "y": 637
        },
        {
          "x": 1005,
          "y": 550
        }
      ],
      "centroid": {
        "x": 1075,
        "y": 592
      },
      "neighbors": [
        "nottinghamshire",
        "lincolnshire",
        "leicestershire",
        "norfolk",
        "northamptonshire",
        "suffolk",
        "hertfordshire",
        "essex"
      ]
    },
    {
      "id": "suffolk",
      "name": "Suffolk",
      "polygon": [
        {
          "x": 1245,
          "y": 736
        },
        {
          "x": 1133,
          "y": 652
        },
        {
          "x": 1152,
          "y": 576
        },
        {
          "x": 1280,
          "y": 586
        },
        {
          "x": 1295,
          "y": 649
        }
      ],
      "centroid": {
        "x": 1217,
        "y": 642
      },
      "neighbors": [
        "norfolk",
        "cambridgeshire",
        "essex"
      ]
    },
    {
      "id": "gloucestershire",
      "name": "Gloucestershire",
      "polygon": [
        {
          "x": 716,
          "y": 689
        },
        {
          "x": 626,
          "y": 818
        },
        {
          "x": 538,
          "y": 719
        },
        {
          "x": 665,
          "y": 624
        },
        {
          "x": 677,
          "y": 623
        }
      ],
      "centroid": {
        "x": 633,
        "y": 715
      },
      "neighbors": [
        "shropshire",
        "herefordshire",
        "warwickshire",
        "somerset",
        "wiltshire"
      ]
    },
    {
      "id": "oxfordshire",
      "name": "Oxfordshire",
      "polygon": [
        {
          "x": 865,
          "y": 641
        },
        {
          "x": 915,
          "y": 702
        },
        {
          "x": 915,
          "y": 722
        },
        {
          "x": 871,
          "y": 781
        },
        {
          "x": 804,
          "y": 790
        },
        {
          "x": 737,
          "y": 698
        }
      ],
      "centroid": {
        "x": 834,
        "y": 718
      },
      "neighbors": [
        "warwickshire",
        "northamptonshire",
        "hertfordshire",
        "wiltshire",
        "surrey",
        "hampshire"
      ]
    },
    {
      "id": "hertfordshire",
      "name": "Hertfordshire",
      "polygon": [
        {
          "x": 915,
          "y": 702
        },
        {
          "x": 1012,
          "y": 637
        },
        {
          "x": 1072,
          "y": 686
        },
        {
          "x": 1065,
          "y": 781
        },
        {
          "x": 1032,
          "y": 787
        },
        {
          "x": 915,
          "y": 722
        }
      ],
      "centroid": {
        "x": 1005,
        "y": 714
      },
      "neighbors": [
        "northamptonshire",
        "cambridgeshire",
        "oxfordshire",
        "essex",
        "surrey",
        "sussex"
      ]
    },
    {
      "id": "essex",
      "name": "Essex",
      "polygon": [
        {
          "x": 1072,
          "y": 686
        },
        {
          "x": 1133,
          "y": 652
        },
        {
          "x": 1245,
          "y": 736
        },
        {
          "x": 1245,
          "y": 744
        },
        {
          "x": 1069,
          "y": 783
        },
        {
          "x": 1065,
          "y": 781
        }
      ],
      "centroid": {
        "x": 1138,
        "y": 722
      },
      "neighbors": [
        "cambridgeshire",
        "suffolk",
        "hertfordshire",
        "kent",
        "sussex"
      ]
    },
    {
      "id": "somerset",
      "name": "Somerset",
      "polygon": [
        {
          "x": 538,
          "y": 719
        },
        {
          "x": 626,
          "y": 818
        },
        {
          "x": 635,
          "y": 977
        },
        {
          "x": 602,
          "y": 1000
        },
        {
          "x": 554,
          "y": 1000
        },
        {
          "x": 387,
          "y": 690
        }
      ],
      "centroid": {
        "x": 536,
        "y": 839
      },
      "neighbors": [
        "herefordshire",
        "gloucestershire",
        "wiltshire",
        "devon"
      ]
    },
    {
      "id": "wiltshire",
      "name": "Wiltshire",
      "polygon": [
        {
          "x": 737,
          "y": 698
        },
        {
          "x": 804,
          "y": 790
        },
        {
          "x": 708,
          "y": 968
        },
        {
          "x": 635,
          "y": 977
        },
        {
          "x": 626,
          "y": 818
        },
        {
          "x": 716,
          "y": 689
        }
      ],
      "centroid": {
        "x": 704,
        "y": 837
      },
      "neighbors": [
        "warwickshire",
        "gloucestershire",
        "oxfordshire",
        "somerset",
        "hampshire"
      ]
    },
    {
      "id": "surrey",
      "name": "Surrey",
      "polygon": [
        {
          "x": 915,
          "y": 722
        },
        {
          "x": 1032,
          "y": 787
        },
        {
          "x": 938,
          "y": 894
        },
        {
          "x": 871,
          "y": 781
        }
      ],
      "centroid": {
        "x": 944,
        "y": 800
      },
      "neighbors": [
        "oxfordshire",
        "hertfordshire",
        "hampshire",
        "sussex"
      ]
    },
    {
      "id": "kent",
      "name": "Kent",
      "polygon": [
        {
          "x": 1069,
          "y": 783
        },
        {
          "x": 1245,
          "y": 744
        },
        {
          "x": 1258,
          "y": 774
        },
        {
          "x": 1230,
          "y": 872
        },
        {
          "x": 1141,
          "y": 920
        },
        {
          "x": 1131,
          "y": 919
        }
      ],
      "centroid": {
        "x": 1169,
        "y": 824
      },
      "neighbors": [
        "essex",
        "sussex"
      ]
    },
    {
      "id": "hampshire",
      "name": "Hampshire",
      "polygon": [
        {
          "x": 871,
          "y": 781
        },
        {
          "x": 938,
          "y": 894
        },
        {
          "x": 936,
          "y": 945
        },
        {
          "x": 744,
          "y": 979
        },
        {
          "x": 708,
          "y": 968
        },
        {
          "x": 804,
          "y": 790
        }
      ],
      "centroid": {
        "x": 832,
        "y": 890
      },
      "neighbors": [
        "oxfordshire",
        "wiltshire",
        "surrey",
        "sussex"
      ]
    },
    {
      "id": "sussex",
      "name": "Sussex",
      "polygon": [
        {
          "x": 1065,
          "y": 781
        },
        {
          "x": 1069,
          "y": 783
        },
        {
          "x": 1131,
          "y": 919
        },
        {
          "x": 1052,
          "y": 968
        },
        {
          "x": 947,
          "y": 953
        },
        {
          "x": 936,
          "y": 945
        },
        {
          "x": 938,
          "y": 894
        },
        {
          "x": 1032,
          "y": 787
        }
      ],
      "centroid": {
        "x": 1032,
        "y": 887
      },
      "neighbors": [
        "hertfordshire",
        "essex",
        "surrey",
        "kent",
        "hampshire"
      ]
    },
    {
      "id": "devon",
      "name": "Devon",
      "polygon": [
        {
          "x": 387,
          "y": 690
        },
        {
          "x": 554,
          "y": 1000
        },
        {
          "x": 361,
          "y": 1000
        },
        {
          "x": 276,
          "y": 702
        },
        {
          "x": 325,
          "y": 647
        }
      ],
      "centroid": {
        "x": 396,
        "y": 851
      },
      "neighbors": [
        "herefordshire",
        "somerset",
        "cornwall"
      ]
    },
    {
      "id": "cornwall",
      "name": "Cornwall",
      "polygon": [
        {
          "x": 276,
          "y": 702
        },
        {
          "x": 361,
          "y": 1000
        },
        {
          "x": 209,
          "y": 1000
        },
        {
          "x": 150,
          "y": 865
        },
        {
          "x": 238,
          "y": 722
        }
      ],
      "centroid": {
        "x": 254,
        "y": 878
      },
      "neighbors": [
        "devon"
      ]
    }
  ]
};
